trigger:
  branches:
    include:
      - main  # or your deployment branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'RBKC-SBOX-LZ-UKBP'
  appName: 'mosaic-ui'
  resourceGroup: 'mosaic-rg'
  packagePath: 'frontend'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    package: '$(packagePath)'
    runtimeStack: 'PYTHON|3.10'
    startupCommand: './startup.sh'
